sonar.projectKey=expense-hub-web
sonar.projectName=Smart Travel and Expense Hub - Web Frontend
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
